package com.jihelife.pojo;

public class DictCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.provinceid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Integer provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.city_id
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.cname
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.officialName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String officialname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.ctripName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String ctripname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.cPy
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String cpy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.cJP
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String cjp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.cfrl
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String cfrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.hot
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.idx
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.cityType
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Integer citytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.lat
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Double lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.lon
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Double lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_city.placeid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Integer placeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.provinceid
     *
     * @return the value of dict_city.provinceid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.provinceid
     *
     * @param provinceid the value for dict_city.provinceid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.city_id
     *
     * @return the value of dict_city.city_id
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.city_id
     *
     * @param cityId the value for dict_city.city_id
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.cname
     *
     * @return the value of dict_city.cname
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.cname
     *
     * @param cname the value for dict_city.cname
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.officialName
     *
     * @return the value of dict_city.officialName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getOfficialname() {
        return officialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.officialName
     *
     * @param officialname the value for dict_city.officialName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setOfficialname(String officialname) {
        this.officialname = officialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.ctripName
     *
     * @return the value of dict_city.ctripName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getCtripname() {
        return ctripname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.ctripName
     *
     * @param ctripname the value for dict_city.ctripName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCtripname(String ctripname) {
        this.ctripname = ctripname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.cPy
     *
     * @return the value of dict_city.cPy
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getCpy() {
        return cpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.cPy
     *
     * @param cpy the value for dict_city.cPy
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCpy(String cpy) {
        this.cpy = cpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.cJP
     *
     * @return the value of dict_city.cJP
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getCjp() {
        return cjp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.cJP
     *
     * @param cjp the value for dict_city.cJP
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCjp(String cjp) {
        this.cjp = cjp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.cfrl
     *
     * @return the value of dict_city.cfrl
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getCfrl() {
        return cfrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.cfrl
     *
     * @param cfrl the value for dict_city.cfrl
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCfrl(String cfrl) {
        this.cfrl = cfrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.hot
     *
     * @return the value of dict_city.hot
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.hot
     *
     * @param hot the value for dict_city.hot
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setHot(String hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.idx
     *
     * @return the value of dict_city.idx
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.idx
     *
     * @param idx the value for dict_city.idx
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.cityType
     *
     * @return the value of dict_city.cityType
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Integer getCitytype() {
        return citytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.cityType
     *
     * @param citytype the value for dict_city.cityType
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setCitytype(Integer citytype) {
        this.citytype = citytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.lat
     *
     * @return the value of dict_city.lat
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.lat
     *
     * @param lat the value for dict_city.lat
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.lon
     *
     * @return the value of dict_city.lon
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.lon
     *
     * @param lon the value for dict_city.lon
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_city.placeid
     *
     * @return the value of dict_city.placeid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Integer getPlaceid() {
        return placeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_city.placeid
     *
     * @param placeid the value for dict_city.placeid
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setPlaceid(Integer placeid) {
        this.placeid = placeid;
    }
}