package com.jihelife.pojo;

import java.util.ArrayList;
import java.util.List;

public class DictCityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public DictCityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProvinceidIsNull() {
            addCriterion("provinceid is null");
            return (Criteria) this;
        }

        public Criteria andProvinceidIsNotNull() {
            addCriterion("provinceid is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceidEqualTo(Integer value) {
            addCriterion("provinceid =", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotEqualTo(Integer value) {
            addCriterion("provinceid <>", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidGreaterThan(Integer value) {
            addCriterion("provinceid >", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("provinceid >=", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidLessThan(Integer value) {
            addCriterion("provinceid <", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidLessThanOrEqualTo(Integer value) {
            addCriterion("provinceid <=", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidIn(List<Integer> values) {
            addCriterion("provinceid in", values, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotIn(List<Integer> values) {
            addCriterion("provinceid not in", values, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidBetween(Integer value1, Integer value2) {
            addCriterion("provinceid between", value1, value2, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotBetween(Integer value1, Integer value2) {
            addCriterion("provinceid not between", value1, value2, "provinceid");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cname is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cname is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cname =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cname <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cname >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cname >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cname <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cname <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cname like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cname not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cname in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cname not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cname between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cname not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameIsNull() {
            addCriterion("officialName is null");
            return (Criteria) this;
        }

        public Criteria andOfficialnameIsNotNull() {
            addCriterion("officialName is not null");
            return (Criteria) this;
        }

        public Criteria andOfficialnameEqualTo(String value) {
            addCriterion("officialName =", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameNotEqualTo(String value) {
            addCriterion("officialName <>", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameGreaterThan(String value) {
            addCriterion("officialName >", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameGreaterThanOrEqualTo(String value) {
            addCriterion("officialName >=", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameLessThan(String value) {
            addCriterion("officialName <", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameLessThanOrEqualTo(String value) {
            addCriterion("officialName <=", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameLike(String value) {
            addCriterion("officialName like", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameNotLike(String value) {
            addCriterion("officialName not like", value, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameIn(List<String> values) {
            addCriterion("officialName in", values, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameNotIn(List<String> values) {
            addCriterion("officialName not in", values, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameBetween(String value1, String value2) {
            addCriterion("officialName between", value1, value2, "officialname");
            return (Criteria) this;
        }

        public Criteria andOfficialnameNotBetween(String value1, String value2) {
            addCriterion("officialName not between", value1, value2, "officialname");
            return (Criteria) this;
        }

        public Criteria andCtripnameIsNull() {
            addCriterion("ctripName is null");
            return (Criteria) this;
        }

        public Criteria andCtripnameIsNotNull() {
            addCriterion("ctripName is not null");
            return (Criteria) this;
        }

        public Criteria andCtripnameEqualTo(String value) {
            addCriterion("ctripName =", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameNotEqualTo(String value) {
            addCriterion("ctripName <>", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameGreaterThan(String value) {
            addCriterion("ctripName >", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameGreaterThanOrEqualTo(String value) {
            addCriterion("ctripName >=", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameLessThan(String value) {
            addCriterion("ctripName <", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameLessThanOrEqualTo(String value) {
            addCriterion("ctripName <=", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameLike(String value) {
            addCriterion("ctripName like", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameNotLike(String value) {
            addCriterion("ctripName not like", value, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameIn(List<String> values) {
            addCriterion("ctripName in", values, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameNotIn(List<String> values) {
            addCriterion("ctripName not in", values, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameBetween(String value1, String value2) {
            addCriterion("ctripName between", value1, value2, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCtripnameNotBetween(String value1, String value2) {
            addCriterion("ctripName not between", value1, value2, "ctripname");
            return (Criteria) this;
        }

        public Criteria andCpyIsNull() {
            addCriterion("cPy is null");
            return (Criteria) this;
        }

        public Criteria andCpyIsNotNull() {
            addCriterion("cPy is not null");
            return (Criteria) this;
        }

        public Criteria andCpyEqualTo(String value) {
            addCriterion("cPy =", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyNotEqualTo(String value) {
            addCriterion("cPy <>", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyGreaterThan(String value) {
            addCriterion("cPy >", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyGreaterThanOrEqualTo(String value) {
            addCriterion("cPy >=", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyLessThan(String value) {
            addCriterion("cPy <", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyLessThanOrEqualTo(String value) {
            addCriterion("cPy <=", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyLike(String value) {
            addCriterion("cPy like", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyNotLike(String value) {
            addCriterion("cPy not like", value, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyIn(List<String> values) {
            addCriterion("cPy in", values, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyNotIn(List<String> values) {
            addCriterion("cPy not in", values, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyBetween(String value1, String value2) {
            addCriterion("cPy between", value1, value2, "cpy");
            return (Criteria) this;
        }

        public Criteria andCpyNotBetween(String value1, String value2) {
            addCriterion("cPy not between", value1, value2, "cpy");
            return (Criteria) this;
        }

        public Criteria andCjpIsNull() {
            addCriterion("cJP is null");
            return (Criteria) this;
        }

        public Criteria andCjpIsNotNull() {
            addCriterion("cJP is not null");
            return (Criteria) this;
        }

        public Criteria andCjpEqualTo(String value) {
            addCriterion("cJP =", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpNotEqualTo(String value) {
            addCriterion("cJP <>", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpGreaterThan(String value) {
            addCriterion("cJP >", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpGreaterThanOrEqualTo(String value) {
            addCriterion("cJP >=", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpLessThan(String value) {
            addCriterion("cJP <", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpLessThanOrEqualTo(String value) {
            addCriterion("cJP <=", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpLike(String value) {
            addCriterion("cJP like", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpNotLike(String value) {
            addCriterion("cJP not like", value, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpIn(List<String> values) {
            addCriterion("cJP in", values, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpNotIn(List<String> values) {
            addCriterion("cJP not in", values, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpBetween(String value1, String value2) {
            addCriterion("cJP between", value1, value2, "cjp");
            return (Criteria) this;
        }

        public Criteria andCjpNotBetween(String value1, String value2) {
            addCriterion("cJP not between", value1, value2, "cjp");
            return (Criteria) this;
        }

        public Criteria andCfrlIsNull() {
            addCriterion("cfrl is null");
            return (Criteria) this;
        }

        public Criteria andCfrlIsNotNull() {
            addCriterion("cfrl is not null");
            return (Criteria) this;
        }

        public Criteria andCfrlEqualTo(String value) {
            addCriterion("cfrl =", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlNotEqualTo(String value) {
            addCriterion("cfrl <>", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlGreaterThan(String value) {
            addCriterion("cfrl >", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlGreaterThanOrEqualTo(String value) {
            addCriterion("cfrl >=", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlLessThan(String value) {
            addCriterion("cfrl <", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlLessThanOrEqualTo(String value) {
            addCriterion("cfrl <=", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlLike(String value) {
            addCriterion("cfrl like", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlNotLike(String value) {
            addCriterion("cfrl not like", value, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlIn(List<String> values) {
            addCriterion("cfrl in", values, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlNotIn(List<String> values) {
            addCriterion("cfrl not in", values, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlBetween(String value1, String value2) {
            addCriterion("cfrl between", value1, value2, "cfrl");
            return (Criteria) this;
        }

        public Criteria andCfrlNotBetween(String value1, String value2) {
            addCriterion("cfrl not between", value1, value2, "cfrl");
            return (Criteria) this;
        }

        public Criteria andHotIsNull() {
            addCriterion("hot is null");
            return (Criteria) this;
        }

        public Criteria andHotIsNotNull() {
            addCriterion("hot is not null");
            return (Criteria) this;
        }

        public Criteria andHotEqualTo(String value) {
            addCriterion("hot =", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotEqualTo(String value) {
            addCriterion("hot <>", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThan(String value) {
            addCriterion("hot >", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThanOrEqualTo(String value) {
            addCriterion("hot >=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThan(String value) {
            addCriterion("hot <", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThanOrEqualTo(String value) {
            addCriterion("hot <=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLike(String value) {
            addCriterion("hot like", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotLike(String value) {
            addCriterion("hot not like", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotIn(List<String> values) {
            addCriterion("hot in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotIn(List<String> values) {
            addCriterion("hot not in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotBetween(String value1, String value2) {
            addCriterion("hot between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotBetween(String value1, String value2) {
            addCriterion("hot not between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andIdxIsNull() {
            addCriterion("idx is null");
            return (Criteria) this;
        }

        public Criteria andIdxIsNotNull() {
            addCriterion("idx is not null");
            return (Criteria) this;
        }

        public Criteria andIdxEqualTo(Integer value) {
            addCriterion("idx =", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotEqualTo(Integer value) {
            addCriterion("idx <>", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThan(Integer value) {
            addCriterion("idx >", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("idx >=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThan(Integer value) {
            addCriterion("idx <", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThanOrEqualTo(Integer value) {
            addCriterion("idx <=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxIn(List<Integer> values) {
            addCriterion("idx in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotIn(List<Integer> values) {
            addCriterion("idx not in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxBetween(Integer value1, Integer value2) {
            addCriterion("idx between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("idx not between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andCitytypeIsNull() {
            addCriterion("cityType is null");
            return (Criteria) this;
        }

        public Criteria andCitytypeIsNotNull() {
            addCriterion("cityType is not null");
            return (Criteria) this;
        }

        public Criteria andCitytypeEqualTo(Integer value) {
            addCriterion("cityType =", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeNotEqualTo(Integer value) {
            addCriterion("cityType <>", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeGreaterThan(Integer value) {
            addCriterion("cityType >", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("cityType >=", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeLessThan(Integer value) {
            addCriterion("cityType <", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeLessThanOrEqualTo(Integer value) {
            addCriterion("cityType <=", value, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeIn(List<Integer> values) {
            addCriterion("cityType in", values, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeNotIn(List<Integer> values) {
            addCriterion("cityType not in", values, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeBetween(Integer value1, Integer value2) {
            addCriterion("cityType between", value1, value2, "citytype");
            return (Criteria) this;
        }

        public Criteria andCitytypeNotBetween(Integer value1, Integer value2) {
            addCriterion("cityType not between", value1, value2, "citytype");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("lat is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("lat is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(Double value) {
            addCriterion("lat =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(Double value) {
            addCriterion("lat <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(Double value) {
            addCriterion("lat >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(Double value) {
            addCriterion("lat >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(Double value) {
            addCriterion("lat <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(Double value) {
            addCriterion("lat <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<Double> values) {
            addCriterion("lat in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<Double> values) {
            addCriterion("lat not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(Double value1, Double value2) {
            addCriterion("lat between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(Double value1, Double value2) {
            addCriterion("lat not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLonIsNull() {
            addCriterion("lon is null");
            return (Criteria) this;
        }

        public Criteria andLonIsNotNull() {
            addCriterion("lon is not null");
            return (Criteria) this;
        }

        public Criteria andLonEqualTo(Double value) {
            addCriterion("lon =", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonNotEqualTo(Double value) {
            addCriterion("lon <>", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonGreaterThan(Double value) {
            addCriterion("lon >", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonGreaterThanOrEqualTo(Double value) {
            addCriterion("lon >=", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonLessThan(Double value) {
            addCriterion("lon <", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonLessThanOrEqualTo(Double value) {
            addCriterion("lon <=", value, "lon");
            return (Criteria) this;
        }

        public Criteria andLonIn(List<Double> values) {
            addCriterion("lon in", values, "lon");
            return (Criteria) this;
        }

        public Criteria andLonNotIn(List<Double> values) {
            addCriterion("lon not in", values, "lon");
            return (Criteria) this;
        }

        public Criteria andLonBetween(Double value1, Double value2) {
            addCriterion("lon between", value1, value2, "lon");
            return (Criteria) this;
        }

        public Criteria andLonNotBetween(Double value1, Double value2) {
            addCriterion("lon not between", value1, value2, "lon");
            return (Criteria) this;
        }

        public Criteria andPlaceidIsNull() {
            addCriterion("placeid is null");
            return (Criteria) this;
        }

        public Criteria andPlaceidIsNotNull() {
            addCriterion("placeid is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceidEqualTo(Integer value) {
            addCriterion("placeid =", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotEqualTo(Integer value) {
            addCriterion("placeid <>", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThan(Integer value) {
            addCriterion("placeid >", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("placeid >=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThan(Integer value) {
            addCriterion("placeid <", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThanOrEqualTo(Integer value) {
            addCriterion("placeid <=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidIn(List<Integer> values) {
            addCriterion("placeid in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotIn(List<Integer> values) {
            addCriterion("placeid not in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidBetween(Integer value1, Integer value2) {
            addCriterion("placeid between", value1, value2, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotBetween(Integer value1, Integer value2) {
            addCriterion("placeid not between", value1, value2, "placeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_city
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 17 14:04:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}