package com.jihelife.pojo;

public class DictProvince {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_province.ProvinceID
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private Long provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_province.ProvinceName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    private String provincename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_province.ProvinceID
     *
     * @return the value of dict_province.ProvinceID
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public Long getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_province.ProvinceID
     *
     * @param provinceid the value for dict_province.ProvinceID
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setProvinceid(Long provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_province.ProvinceName
     *
     * @return the value of dict_province.ProvinceName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_province.ProvinceName
     *
     * @param provincename the value for dict_province.ProvinceName
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }



}