package com.jihelife.pojo;

import java.util.Date;

public class SysParametersV12 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.param_key
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.param_value
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.description
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.param_type
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private String paramType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.update_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameters_v12.create_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.param_key
     *
     * @return the value of sys_parameters_v12.param_key
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.param_key
     *
     * @param paramKey the value for sys_parameters_v12.param_key
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.param_value
     *
     * @return the value of sys_parameters_v12.param_value
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.param_value
     *
     * @param paramValue the value for sys_parameters_v12.param_value
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.description
     *
     * @return the value of sys_parameters_v12.description
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.description
     *
     * @param description the value for sys_parameters_v12.description
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.param_type
     *
     * @return the value of sys_parameters_v12.param_type
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.param_type
     *
     * @param paramType the value for sys_parameters_v12.param_type
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.update_time
     *
     * @return the value of sys_parameters_v12.update_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.update_time
     *
     * @param updateTime the value for sys_parameters_v12.update_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameters_v12.create_time
     *
     * @return the value of sys_parameters_v12.create_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameters_v12.create_time
     *
     * @param createTime the value for sys_parameters_v12.create_time
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}