package com.jihelife.pojo;

public class TSmsSignature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_signature.signature_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String signatureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_signature.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String site;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_signature.signature_name
     *
     * @return the value of t_sms_signature.signature_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getSignatureName() {
        return signatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_signature.signature_name
     *
     * @param signatureName the value for t_sms_signature.signature_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSignatureName(String signatureName) {
        this.signatureName = signatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_signature.site
     *
     * @return the value of t_sms_signature.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_signature.site
     *
     * @param site the value for t_sms_signature.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSite(String site) {
        this.site = site;
    }


}