package com.jihelife.pojo;

public class TSmsTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.template_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.template_num
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String templateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.template_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String templateContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.template_mark
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String templateMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.sign_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer signId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_template.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.template_id
     *
     * @return the value of t_sms_template.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.template_id
     *
     * @param templateId the value for t_sms_template.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.template_name
     *
     * @return the value of t_sms_template.template_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.template_name
     *
     * @param templateName the value for t_sms_template.template_name
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.template_num
     *
     * @return the value of t_sms_template.template_num
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getTemplateNum() {
        return templateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.template_num
     *
     * @param templateNum the value for t_sms_template.template_num
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateNum(String templateNum) {
        this.templateNum = templateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.template_content
     *
     * @return the value of t_sms_template.template_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.template_content
     *
     * @param templateContent the value for t_sms_template.template_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.template_mark
     *
     * @return the value of t_sms_template.template_mark
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getTemplateMark() {
        return templateMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.template_mark
     *
     * @param templateMark the value for t_sms_template.template_mark
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateMark(String templateMark) {
        this.templateMark = templateMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.sign_id
     *
     * @return the value of t_sms_template.sign_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.sign_id
     *
     * @param signId the value for t_sms_template.sign_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_template.hotel_id
     *
     * @return the value of t_sms_template.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_template.hotel_id
     *
     * @param hotelId the value for t_sms_template.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
}