package com.jihelife.pojo;

import java.util.Date;

public class TSmsRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.user_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.account_phone
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String accountPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.group_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.send_time
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.send_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String sendContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.record_status
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private Integer recordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_record.error_code
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    private String errorCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.user_id
     *
     * @return the value of t_sms_record.user_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.user_id
     *
     * @param userId the value for t_sms_record.user_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.account_phone
     *
     * @return the value of t_sms_record.account_phone
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getAccountPhone() {
        return accountPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.account_phone
     *
     * @param accountPhone the value for t_sms_record.account_phone
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setAccountPhone(String accountPhone) {
        this.accountPhone = accountPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.hotel_id
     *
     * @return the value of t_sms_record.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.hotel_id
     *
     * @param hotelId the value for t_sms_record.hotel_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.group_id
     *
     * @return the value of t_sms_record.group_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.group_id
     *
     * @param groupId the value for t_sms_record.group_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.site
     *
     * @return the value of t_sms_record.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.site
     *
     * @param site the value for t_sms_record.site
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSite(String site) {
        this.site = site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.template_id
     *
     * @return the value of t_sms_record.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.template_id
     *
     * @param templateId the value for t_sms_record.template_id
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.send_time
     *
     * @return the value of t_sms_record.send_time
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.send_time
     *
     * @param sendTime the value for t_sms_record.send_time
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.send_content
     *
     * @return the value of t_sms_record.send_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getSendContent() {
        return sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.send_content
     *
     * @param sendContent the value for t_sms_record.send_content
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.record_status
     *
     * @return the value of t_sms_record.record_status
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.record_status
     *
     * @param recordStatus the value for t_sms_record.record_status
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_record.error_code
     *
     * @return the value of t_sms_record.error_code
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_record.error_code
     *
     * @param errorCode the value for t_sms_record.error_code
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
}