package com.jihelife.pojo;

import java.util.ArrayList;
import java.util.List;

public class TSmsSignatureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public TSmsSignatureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSignatureNameIsNull() {
            addCriterion("signature_name is null");
            return (Criteria) this;
        }

        public Criteria andSignatureNameIsNotNull() {
            addCriterion("signature_name is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureNameEqualTo(String value) {
            addCriterion("signature_name =", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameNotEqualTo(String value) {
            addCriterion("signature_name <>", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameGreaterThan(String value) {
            addCriterion("signature_name >", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameGreaterThanOrEqualTo(String value) {
            addCriterion("signature_name >=", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameLessThan(String value) {
            addCriterion("signature_name <", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameLessThanOrEqualTo(String value) {
            addCriterion("signature_name <=", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameLike(String value) {
            addCriterion("signature_name like", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameNotLike(String value) {
            addCriterion("signature_name not like", value, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameIn(List<String> values) {
            addCriterion("signature_name in", values, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameNotIn(List<String> values) {
            addCriterion("signature_name not in", values, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameBetween(String value1, String value2) {
            addCriterion("signature_name between", value1, value2, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSignatureNameNotBetween(String value1, String value2) {
            addCriterion("signature_name not between", value1, value2, "signatureName");
            return (Criteria) this;
        }

        public Criteria andSiteIsNull() {
            addCriterion("site is null");
            return (Criteria) this;
        }

        public Criteria andSiteIsNotNull() {
            addCriterion("site is not null");
            return (Criteria) this;
        }

        public Criteria andSiteEqualTo(String value) {
            addCriterion("site =", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotEqualTo(String value) {
            addCriterion("site <>", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThan(String value) {
            addCriterion("site >", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThanOrEqualTo(String value) {
            addCriterion("site >=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThan(String value) {
            addCriterion("site <", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThanOrEqualTo(String value) {
            addCriterion("site <=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLike(String value) {
            addCriterion("site like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotLike(String value) {
            addCriterion("site not like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteIn(List<String> values) {
            addCriterion("site in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotIn(List<String> values) {
            addCriterion("site not in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteBetween(String value1, String value2) {
            addCriterion("site between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotBetween(String value1, String value2) {
            addCriterion("site not between", value1, value2, "site");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms_signature
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 22 15:31:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms_signature
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}