package com.jihelife.mapper;

import com.jihelife.pojo.DictCity;
import com.jihelife.pojo.DictCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface DictCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    long countByExample(DictCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int deleteByExample(DictCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int insert(DictCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int insertSelective(DictCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    List<DictCity> selectByExample(DictCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictCity record, @Param("example") DictCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_city
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByExample(@Param("record") DictCity record, @Param("example") DictCityExample example);

    /*根据provinceId查询city*/
    @Select("select provinceid,city_id as cityId,cname,officialName,ctripName from dict_city where provinceid=#{provinceId}")
    List<DictCity> selectCityByProId(@Param("provinceId") int provinceId);
}