package com.jihelife.mapper;

import com.jihelife.pojo.DictHoliday;
import com.jihelife.pojo.DictHolidayExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface DictHolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    long countByExample(DictHolidayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    int deleteByExample(DictHolidayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    int insert(DictHoliday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    int insertSelective(DictHoliday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    List<DictHoliday> selectByExample(DictHolidayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictHoliday record, @Param("example") DictHolidayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_holiday
     *
     * @mbg.generated Wed Jan 24 15:01:54 CST 2018
     */
    int updateByExample(@Param("record") DictHoliday record, @Param("example") DictHolidayExample example);


    List<DictHoliday> queryHolidayAfterToday(@Param("today") Date today);
}