package com.jihelife.mapper;

import com.jihelife.pojo.DictProvince;
import com.jihelife.pojo.DictProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface DictProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    long countByExample(DictProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int deleteByExample(DictProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int deleteByPrimaryKey(Long provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int insert(DictProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int insertSelective(DictProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    List<DictProvince> selectByExample(DictProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    DictProvince selectByPrimaryKey(Long provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictProvince record, @Param("example") DictProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByExample(@Param("record") DictProvince record, @Param("example") DictProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByPrimaryKeySelective(DictProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_province
     *
     * @mbg.generated Wed Jan 17 14:04:36 CST 2018
     */
    int updateByPrimaryKey(DictProvince record);

    @Select("select ProvinceID,ProvinceName from dict_province")
    List<DictProvince> selectAllProvince();
}