package com.jihelife.mapper;

import com.jihelife.pojo.SysParametersV12;
import com.jihelife.pojo.SysParametersV12Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SysParametersV12Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    long countByExample(SysParametersV12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int deleteByExample(SysParametersV12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int insert(SysParametersV12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int insertSelective(SysParametersV12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    List<SysParametersV12> selectByExample(SysParametersV12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    SysParametersV12 selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysParametersV12 record, @Param("example") SysParametersV12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int updateByExample(@Param("record") SysParametersV12 record, @Param("example") SysParametersV12Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int updateByPrimaryKeySelective(SysParametersV12 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbg.generated Thu Jan 04 19:55:44 CST 2018
     */
    int updateByPrimaryKey(SysParametersV12 record);

    /*查询所有参数*/
    List<SysParametersV12> selectAllParams();
}