package com.jihelife.mapper;

import com.jihelife.pojo.SysParameter;
import com.jihelife.pojo.SysParameterExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int countByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int deleteByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int insert(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int insertSelective(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    List<SysParameter> selectByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    SysParameter selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") SysParameter record, @Param("example") SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int updateByExample(@Param("record") SysParameter record, @Param("example") SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameters_v12
     *
     * @mbggenerated Fri Dec 18 10:06:27 GMT+08:00 2015
     */
    int updateByPrimaryKey(SysParameter record);
}