package com.jihelife.mapper;

import com.jihelife.pojo.ReqParameter;
import com.jihelife.pojo.TSmsRecord;
import com.jihelife.pojo.TSmsRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSmsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    long countByExample(TSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int deleteByExample(TSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int insert(TSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int insertSelective(TSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    List<TSmsRecord> selectByExample(TSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSmsRecord record, @Param("example") TSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_record
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int updateByExample(@Param("record") TSmsRecord record, @Param("example") TSmsRecordExample example);

    List<TSmsRecord> querySmsRecord(@Param("param") ReqParameter reqParameter);
}