package com.jihelife.mapper;

import com.jihelife.pojo.TSmsTemplate;
import com.jihelife.pojo.TSmsTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    long countByExample(TSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int deleteByExample(TSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int insert(TSmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int insertSelective(TSmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    List<TSmsTemplate> selectByExample(TSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSmsTemplate record, @Param("example") TSmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_template
     *
     * @mbg.generated Mon Jan 22 15:31:24 CST 2018
     */
    int updateByExample(@Param("record") TSmsTemplate record, @Param("example") TSmsTemplateExample example);


    List<TSmsTemplate> selectTemplateList(@Param("templateId") int templateId);
}